
server:
  port: 9000
spring:
  application:
      name: api-gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: authService
          uri: lb://authService
          predicates:
            - Path=/auth/**
        - id: BasketService
          uri: lb://BasketService
          predicates:
            - Path=basket/**
eureka:
     client:
       initial-instance-info-replication-interval-seconds: 5
       registry-fetch-interval-seconds: 5
       service-url:
         defaultZone: http://localhost:9091/eureka/