server:
  port: 0
spring:
  application:
    name: basket-service
  datasource:
    url: jdbc:mysql://localhost:3306/basket
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
eureka:
  client:
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
