server:
  port: 0

  eureka:
    client:
      instance-info-replication-interval-seconds: 5
      registry-fetch-interval-seconds: 5
      serviceUrl:
        defaultZone: http://localhost:9091/eureka/

spring:
  name: commonService